/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './features/~__root';
import { Route as IndexImport } from './features/~index';
import { Route as GalleryIndexImport } from './features/~gallery/~index';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const GalleryIndexRoute = GalleryIndexImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/gallery/': {
      id: '/gallery/';
      path: '/gallery';
      fullPath: '/gallery';
      preLoaderRoute: typeof GalleryIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/gallery': typeof GalleryIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/gallery': typeof GalleryIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/gallery/': typeof GalleryIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/gallery';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/gallery';
  id: '__root__' | '/' | '/gallery/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  GalleryIndexRoute: typeof GalleryIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/gallery/"
      ]
    },
    "/": {
      "filePath": "~index.tsx"
    },
    "/gallery/": {
      "filePath": "~gallery/~index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
